// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvKUUHfEyNxGSvUoSg_fMzmNbcQ_yFwHs',
    appId: '1:284759277268:web:f8b182d79f948d2926c541',
    messagingSenderId: '284759277268',
    projectId: 'financeflow-app-32440',
    authDomain: 'financeflow-app-32440.firebaseapp.com',
    storageBucket: 'financeflow-app-32440.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7iErzZGj51tYC-LJFCLfdPZdPP6MiEkE',
    appId: '1:284759277268:android:06da0360c1587ab426c541',
    messagingSenderId: '284759277268',
    projectId: 'financeflow-app-32440',
    storageBucket: 'financeflow-app-32440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Ex3yNlKASqTPoSEG-PUPBU9rEBr4huY',
    appId: '1:284759277268:ios:8ea1a1cee52e550e26c541',
    messagingSenderId: '284759277268',
    projectId: 'financeflow-app-32440',
    storageBucket: 'financeflow-app-32440.firebasestorage.app',
    iosBundleId: 'com.example.applicationFinaceflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Ex3yNlKASqTPoSEG-PUPBU9rEBr4huY',
    appId: '1:284759277268:ios:8ea1a1cee52e550e26c541',
    messagingSenderId: '284759277268',
    projectId: 'financeflow-app-32440',
    storageBucket: 'financeflow-app-32440.firebasestorage.app',
    iosBundleId: 'com.example.applicationFinaceflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvKUUHfEyNxGSvUoSg_fMzmNbcQ_yFwHs',
    appId: '1:284759277268:web:5284d13684bf582a26c541',
    messagingSenderId: '284759277268',
    projectId: 'financeflow-app-32440',
    authDomain: 'financeflow-app-32440.firebaseapp.com',
    storageBucket: 'financeflow-app-32440.firebasestorage.app',
  );
}
